name: CouponCodes
main: me.yourmcgeek.coupons.CouponCodes
version: 0.1
description: Create, distribute and redeem coupon codes for your players to earn prizes and rewards!
authors: [YourMCGeek, 2008Choco]

commands:
    coupon:
      description: The central CouponCodes command
      usage: /<command> [create|delete]
      aliases: [coupons]
      
permissions:
    coupons.create:
      description: Grants access to the "/coupon create" command
      default: op
    coupons.delete:
      description: Grants access to the "/coupon delete" command
      default: op
    coupons.redeem:
      description: Grants access to the "/coupon redeem" command
      default: true
    coupons.redeemtoggle:
      description: Grants access to the "/coupons redeemtoggle" command
      default: op
    coupons.list:
      description: Grants access to the "/coupons list" command
      default: true
    coupons.reload:
      description: Grants access to the "/coupons book" command
      default: op