name: CouponCodes
main: me.yourmcgeek.coupons.CouponCodes
version: 0.1
description: A nice plugin that provides a way to award players in a fun mannor!
author: YourMCGeek, 2008Choco
commands:
    coupon:
      description: The central CouponCodes command
      usage: /<command> [create|delete]
      aliases: [coupons]